<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Models\" />
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Remove="Assets\condownloader-mac.png" />
    <AvaloniaResource Remove="Assets\condownloaderbanner-light.png" />
    <AvaloniaResource Remove="Assets\condownloaderbanner.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.1.2" />
    <PackageReference Include="Avalonia.Desktop" Version="11.1.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.1.2" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.1.2" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.1.2" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
    <PackageReference Include="NYoutubeDL" Version="0.11.2" />
    <PackageReference Include="xFFmpeg.NET" Version="7.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="SIADL.Avalonia">
      <HintPath>Dependencies\SIADL.Avalonia.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="Dependencies\Windows\ffmpeg.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Dependencies\Windows\youtube-dl.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
